---
blank_issues_enabled: false
contact_links:
  - about: Translate the documentation into other languages on Crowdin
    name: ğŸ“œ Translate
    url: https://crowdin.com/project/literary-universe
  - about: Do you have a question or feedback?
    name: â“ Questions & Feedback
    url: https://www.literaryuniverse.com/feedback
  - about: Chat on our Discord community
    name: ğŸ—¯ Chat
    url: https://discord.gg/qR6dkFd
  - about: The official Literary Universe website
    name: â„¹ï¸ Website
    url: https://www.literaryuniverse.com/
